spring.application.name=policy-service
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/insurancedb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Add this line - forces JVM timezone instead of OS-detected one
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Party Service URL
party.service.url=http://localhost:8082

# Add this to policy-service application.properties
logging.level.com.insurance.policy_service.client=DEBUG
feign.client.config.default.loggerLevel=full