spring.application.name=party-service
server.port=8082

# Same PostgreSQL container, different schema
spring.datasource.url=jdbc:postgresql://localhost:5432/insurancedb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=party

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

# Fix timezone issue (same as policy-service)
spring.jpa.properties.hibernate.jdbc.time_zone=UTC